[default]
TEST_PATH = 'ospf'
QUESTION_TYPE = 'BASIC' # BASIC 基础集，DETAILED 详细集， MECHANISM 机制集 THEMATIC 主题集
# zlpt
ZLPT_BASE_URL = "https://10.220.49.200"
KEY1 = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCbPqaFZ0lgebihx"
KEY2_ADD = "Cw5wzjkahPKr6ZI2JNTHbHDnNbOn3Cif6GgnMBr44MhQCRPQTF2FgcxBbn3u7eGcEPMT6OZqcLzcmiMCUQRJ2MUbFI+"
PK = "E1vI1f+iuCQ2w8XZhRoRrmb7wBA0L63gnSwXRkJD0baL5zqlQhpSKfSH0t3opAoahwIDAQAB"
# 用户信息
USERNAME = "nrgtest"
PASSWORD = "Admin@123"
DOMAIN = "default"
# label studio
LABEL_STUDIO_URL = "http://localhost:8080"
LABEL_STUDIO_API_KEY = "ad4386c571434507c07f682c34df630a01145bf9"
# 问题配置
CHUNK_SIZE = 600
CHUNK_OVERLAP = 0
# 当使用text计算时的参数
OVERLAP_THRESHOLD = 0.8   # 字符串重叠阈值
SIMILARITY_THRESHOLD = 0.3  # 语义相似度阈值
semantic_weight = 0.9  # 语义匹配权重
MODEL_PATH = 'D:\pyworkplace\git_place\ai-ken\models\bge-base-zh-v1.5'