[default]
# zlpt
ZLPT_BASE_URL = "https://10.220.49.200"
KEY1 = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCbPqaFZ0lgebihx"
KEY2_ADD = "Cw5wzjkahPKr6ZI2JNTHbHDnNbOn3Cif6GgnMBr44MhQCRPQTF2FgcxBbn3u7eGcEPMT6OZqcLzcmiMCUQRJ2MUbFI+"
PK = "E1vI1f+iuCQ2w8XZhRoRrmb7wBA0L63gnSwXRkJD0baL5zqlQhpSKfSH0t3opAoahwIDAQAB"
# 用户信息
USERNAME = "nrgtest"
PASSWORD = "Admin@123"
DOMAIN = "default"
# label studio
LABEL_STUDIO_URL = "http://localhost:8080"
LABEL_STUDIO_API_KEY = "ad4386c571434507c07f682c34df630a01145bf9"
# 问题配置
QUESTION_PATH = "D:\\pyworkplace\\git_place\\ai-ken\\tests\\ospf\\question.json"
